Jahia/LDAP-provider

pom.xml
https://jira.jahia.org/browse/BACKLOG-11952
=> BACKLOG-11952: updated dependency

pom.xml
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-11952 : Update version

pom.xml
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-11952: Make imports mandatory

pom.xml
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-11952 : Fixed dependencies and packaging

LICENSE.txt, pom.xml, src/main/java/org/jahia/services/usermanager/ldap/JahiaLDAPConfig.java, src/main/java/org/jahia/services/usermanager/ldap/JahiaLDAPConfigFactory.java, src/main/java/org/jahia/services/usermanager/ldap/JahiaLDAPConfigManager.java, src/main/java/org/jahia/services/usermanager/ldap/LDAPUserGroupProvider.java, src/main/java/org/jahia/services/usermanager/ldap/LdapProviderConfiguration.java, src/main/java/org/jahia/services/usermanager/ldap/cache/LDAPAbstractCacheEntry.java, src/main/java/org/jahia/services/usermanager/ldap/cache/LDAPCacheManager.java, src/main/java/org/jahia/services/usermanager/ldap/cache/LDAPGroupCacheEntry.java, src/main/java/org/jahia/services/usermanager/ldap/cache/LDAPUserCacheEntry.java, src/main/java/org/jahia/services/usermanager/ldap/communication/LdapTemplateCallback.java, src/main/java/org/jahia/services/usermanager/ldap/communication/LdapTemplateWrapper.java, src/main/java/org/jahia/services/usermanager/ldap/config/AbstractConfig.java, src/main/java/org/jahia/services/usermanager/ldap/config/GroupConfig.java, src/main/java/org/jahia/services/usermanager/ldap/config/UserConfig.java, src/main/resources/META-INF/LICENSE.txt
=> BACKLOG-13158 - Updated license year to 2020

pom.xml
https://jira.jahia.org/browse/BACKLOG-13158
=> BACKLOG-13158 : add spring requirement

pom.xml, src/main/resources/LdapForm.settingsBootstrap3GoogleMaterialStyle.jspf
https://jira.jahia.org/browse/QA-12918
Update documentation link to new page in academy. update signature
=> QA-12918: Update documentation link to new page in academy. 

src/main/java/org/jahia/services/usermanager/ldap/LdapProviderConfiguration.java
https://jira.jahia.org/browse/QA-12452
=> QA-12452: Wrap exception to avoid sending unserialized objects

.circleci/.circleci.settings.xml, .circleci/config.yml, .github/workflows/triggerCircleCIOnPR.yml
https://jira.jahia.org/browse/QA-13351
=> QA-13351: Add CircleCI config

pom.xml
https://jira.jahia.org/browse/QA-13351
=> QA-13351: Update module signature

src/main/resources/userGroupProviderEdit.jsp
https://jira.jahia.org/browse/QA-13351
=> QA-13351: Remove call to System.out.println(...)

pom.xml
https://jira.jahia.org/browse/QA-13627
updated spring-ldap
spring-data-common and spring-security-web are unused, removed
=> QA-13627: cleaned dependencies

pom.xml, src/main/java/org/jahia/services/usermanager/ldap/JahiaLDAPConfig.java
https://jira.jahia.org/browse/QA-13595
Add guava dependency
=> QA-13595 Add guava dependency

src/main/java/org/jahia/services/usermanager/ldap/LDAPUserGroupProvider.java
This reverts commit ca29582e491d16deedf2491c78154118ad620b9e.
=> Revert "Merge pull request #23"

pom.xml, src/main/java/org/jahia/services/usermanager/ldap/JahiaLDAPConfig.java
https://jira.jahia.org/browse/QA-14007
#24 
=> QA-14007: Backport security fixes from QA-13627

src/main/java/org/jahia/services/usermanager/ldap/LDAPUserGroupProvider.java
https://jira.jahia.org/browse/QA-13649
Prevent NPE
=> QA-13649 Break the loop, return empty properties set to prevent NPE

pom.xml
https://jira.jahia.org/browse/QA-13649
Signature update
=> QA-13649 Signature

src/main/java/org/jahia/services/usermanager/ldap/LDAPUserGroupProvider.java
https://jira.jahia.org/browse/BACKLOG-16810
(partially) revert solution of returning empty query as it doesn't seem to work and still returning all results.
Revert back to returning null when building user/group query with incompatible criteria and safely handling null return cases.
=> BACKLOG-16810: Return and catch null objects

pom.xml, src/main/java/org/jahia/services/usermanager/ldap/JahiaLDAPConfig.java, src/main/java/org/jahia/services/usermanager/ldap/JahiaLDAPConfigFactory.java, src/main/java/org/jahia/services/usermanager/ldap/JahiaLDAPConfigManager.java, src/main/java/org/jahia/services/usermanager/ldap/LDAPUserGroupProvider.java, src/main/java/org/jahia/services/usermanager/ldap/LdapProviderConfiguration.java, src/main/java/org/jahia/services/usermanager/ldap/cache/LDAPAbstractCacheEntry.java, src/main/java/org/jahia/services/usermanager/ldap/cache/LDAPCacheManager.java, src/main/java/org/jahia/services/usermanager/ldap/cache/LDAPGroupCacheEntry.java, src/main/java/org/jahia/services/usermanager/ldap/cache/LDAPUserCacheEntry.java, src/main/java/org/jahia/services/usermanager/ldap/communication/LdapTemplateCallback.java, src/main/java/org/jahia/services/usermanager/ldap/communication/LdapTemplateWrapper.java, src/main/java/org/jahia/services/usermanager/ldap/config/AbstractConfig.java, src/main/java/org/jahia/services/usermanager/ldap/config/GroupConfig.java, src/main/java/org/jahia/services/usermanager/ldap/config/UserConfig.java
https://jira.jahia.org/browse/QA-14203
=> QA-14203 - Update copyright year and license header

.circleci/owasp-suppressions.xml, pom.xml
https://jira.jahia.org/browse/BACKLOG-16921
Upgrade spring-ldap and suppress vulnerability warnings, which look not exploitable in the
context of the module
=> BACKLOG-16921: Upgrade spring-ldap

.circleci/owasp-suppressions.xml, pom.xml
https://jira.jahia.org/browse/BACKLOG-16921
Update module signature
=> BACKLOG-16921: Update module signature

.github/workflows/on-code-change.yml, .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1081
Update deprecated steps
=> TECH-1081 Update deprecated steps

.github/dependabot.yml
https://jira.jahia.org/browse/TECH-1127
add dependabot config
=> TECH-1127 add dependabot config

.github/workflows/on-release.yml
For consistency, it was missing in the repo
=> Added release workflow

pom.xml
https://jira.jahia.org/browse/BACKLOG-22362
=> BACKLOG-22362: limit springframework import version

pom.xml
https://jira.jahia.org/browse/TECH-1395
Exclude provided transitive dependencies as they otherwise get listed in SBOM with a wrong version and lead to many false positive vulnerabilities.
=> TECH-1395: Exclude provided transitive dependencies

.github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1658
=> TECH-1658: Use JDK 11 image in the sonar workflow

.github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1740
=> TECH-1740: Use JDK8 image in sonar wf

pom.xml
https://jira.jahia.org/browse/BACKLOG-22643
=> BACKLOG-22643: Add dependency to external-provider

pom.xml
https://jira.jahia.org/browse/BACKLOG-22643
=> BACKLOG-22643: Update version

.github/maven.settings.xml
https://jira.jahia.org/browse/BACKLOG-22653
=> BACKLOG-22653: Add missing staging credentials

.github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1639
=> TECH-1639: Updated version of the GitHub Actions
